
import React, { useState } from 'react';
import { LogEntry } from '../types';
import { analyzeLogs } from '../services/geminiService';
import AnalyzeIcon from './icons/AnalyzeIcon';

interface AnalysisViewProps {
  logs: LogEntry[];
}

const AnalysisView: React.FC<AnalysisViewProps> = ({ logs }) => {
  const [analysis, setAnalysis] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleAnalyze = async () => {
    setIsLoading(true);
    setError('');
    setAnalysis('');
    try {
      const result = await analyzeLogs(logs);
      setAnalysis(result);
    } catch (e) {
      const err = e as Error;
      setError(err.message || 'An unknown error occurred.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="bg-white dark:bg-slate-800 p-6 rounded-lg shadow-lg">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4">
        <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">Gemini Log Analysis</h2>
        <button
          onClick={handleAnalyze}
          disabled={isLoading || logs.length === 0}
          className="mt-2 sm:mt-0 flex items-center justify-center gap-2 px-4 py-2 bg-primary-600 text-white font-semibold rounded-md shadow-sm hover:bg-primary-700 disabled:bg-slate-400 disabled:cursor-not-allowed transition-colors"
        >
          {isLoading ? (
            <>
              <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Analyzing...
            </>
          ) : (
            <>
              <AnalyzeIcon />
              Analyze My Logs
            </>
          )}
        </button>
      </div>
      
      {logs.length === 0 && (
         <p className="text-center text-slate-500 dark:text-slate-400 py-8">
            Please add some medication and symptom logs before running the analysis.
          </p>
      )}

      {error && (
        <div className="bg-red-100 dark:bg-red-900/50 border-l-4 border-red-500 text-red-700 dark:text-red-200 p-4" role="alert">
          <p className="font-bold">Error</p>
          <p>{error}</p>
        </div>
      )}

      {analysis && (
         <div className="mt-4 p-4 bg-slate-50 dark:bg-slate-900/50 rounded-lg">
            <h3 className="font-semibold text-lg mb-2 text-slate-800 dark:text-slate-100">Analysis Results</h3>
            <div className="prose prose-slate dark:prose-invert max-w-none" dangerouslySetInnerHTML={{ __html: analysis.replace(/\n/g, '<br />') }} />
             <div className="mt-4 p-3 bg-amber-100 dark:bg-amber-900/50 border-l-4 border-amber-500 text-amber-800 dark:text-amber-200 text-sm">
              <strong>Disclaimer:</strong> This analysis is generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice. Please consult with your doctor or a qualified healthcare provider regarding your health and treatment.
            </div>
         </div>
      )}

      {!analysis && !isLoading && logs.length > 0 && (
          <div className="text-center py-8">
             <p className="text-slate-500 dark:text-slate-400">Click the "Analyze My Logs" button to get AI-powered insights on your data.</p>
          </div>
      )}

    </div>
  );
};

export default AnalysisView;
